modbus.ip = 127.0.0.1

modbus.port = 502

modbus.protocol = tcp

modbus.unit_id = 255

modbus.callback = modbus_demo_callback

# DGIoT网关分类ID配置
modbus.category = 5ca6049839

# DGIoT控制器厂商配置
modbus.dtutype = DGIOT
