// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dlink.proto

package io.grpc.examples.dlink;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dgiot.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();
}
