##--------------------------------------------------------------------
## delete field
##--------------------------------------------------------------------
parse.delete_field = ACL,objectId,updatedAt,createdAt

##--------------------------------------------------------------------
## parse config
##--------------------------------------------------------------------
parse.parse_server = http://192.168.1.5:1337
parse.parse_path = /parse/
parse.parse_appid = e24089ff4d4c3fa16b55a977f5099057
parse.parse_master_key = 8bb3705609171b88bf01e66fc4333505
parse.parse_js_key = 7d2afa1830cb61b8fe90fcce8880f9f0
parse.parse_rest_key = 2397bf341a0459f398268364bbc4ca56

##--------------------------------------------------------------------
## parse cache
##--------------------------------------------------------------------
## auto_save自动坚持保存时间 单位 毫秒
parse.cache.auto_save = 10000
## max_size 最大存储数量
parse.cache.max_size = 100000
## max_memory 最大内存数，单位byte
parse.cache.max_memory = 1024000
## max_time 最大时间间隔，单位秒
parse.cache.max_time = 60
