##--------------------------------------------------------------------
## delete field
##--------------------------------------------------------------------
parse.delete_field = ACL,objectId,updatedAt,createdAt

##--------------------------------------------------------------------
## parse config
##--------------------------------------------------------------------
parse.parse_server = http://127.0.0.1:1337
parse.parse_path = /parse/
parse.parse_appid = af690d0aca8ab2b99be9e98a2de65547
parse.parse_master_key = 9a3898f4a24854f020db6ea1177e1b8b
parse.parse_js_key = 66448b45960a669d689b545672435fb4
parse.parse_rest_key = abd2401177e5a87fbcd21363a872bcfd

##--------------------------------------------------------------------
## parse cache
##--------------------------------------------------------------------
## auto_save自动坚持保存时间 单位 毫秒
parse.cache.auto_save = 10000
## max_size 最大存储数量
parse.cache.max_size = 100000
## max_memory 最大内存数，单位byte
parse.cache.max_memory = 1024000
## max_time 最大时间间隔，单位秒
parse.cache.max_time = 60
