# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlink.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64link.proto\x12\x05\x64giot\"M\n\x0ePayloadRequest\x12\x14\n\x07product\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\tB\n\n\x08_product\"k\n\x0fPayloadResponse\x12\x12\n\x05topic\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07payload\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03\x61\x63k\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_topicB\n\n\x08_payloadB\x06\n\x04_ack2C\n\x05\x44link\x12:\n\x07Payload\x12\x15.dgiot.PayloadRequest\x1a\x16.dgiot.PayloadResponse\"\x00\x42+\n\x13io.grpc.dgiot.dlinkB\nDlinkProtoP\x01\xa2\x02\x05\x64linkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dlink_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.grpc.dgiot.dlinkB\nDlinkProtoP\001\242\002\005dlink'
  _globals['_PAYLOADREQUEST']._serialized_start=22
  _globals['_PAYLOADREQUEST']._serialized_end=99
  _globals['_PAYLOADRESPONSE']._serialized_start=101
  _globals['_PAYLOADRESPONSE']._serialized_end=208
  _globals['_DLINK']._serialized_start=210
  _globals['_DLINK']._serialized_end=277
# @@protoc_insertion_point(module_scope)
