#aliyun.version= 2017-03-21
#aliyun.live.push_key= <redacted>
#aliyun.live.live_key = <redacted>
#aliyun.live.push_url = rtmp://push.example.com
#aliyun.live.live_url_rtmp = rtmp://live.example.com
#aliyun.live.live_url_http = http://live.example.com
#aliyun.live.signatureVersion= 1.0

aliyun.accessKeyId= <redacted-akid>
aliyun.accessKeySecret= <redacted-aksecret>
#aliyun.domainName= http://vod.cn-shanghai.aliyuncs.com
aliyun.uploadCallbackUrl= http://127.0.0.1:8081
aliyun.uploadHost= http://<your-oss-host>

# 阿里云工业互联网
inplat.host = http://api.inplat.com.cn
inplat.appkey = <redacted>
inplat.appsecret = <redacted>

#百度地图
baidumap.appkey = <redacted>
#百度地图纠偏值
baidumap.lngoffset = 0.00000
baidumap.latoffset = 0.00000


#友盟消息推送
umeng.appkey = <redacted>
umeng.masterkey = <redacted>

#微信小程序
wechat.appid = wx342213131234
wechat.secret = 14a32132143ab6490ff

#微信公众号
wechatpublic.appid = wx342213131234
wechatpublic.secret = 14a32132143ab6490ff

#服务商户号
wechat.sp_mchid = 164123456

#子商户号
wechat.sub_mchid = 164123456

#商户API证书序列号
wechat.serial_no = 3431213443505AC43223C57
#商户API v3密钥
wechat.apiv3 = 8FE123414684E9A9459KP8DFE657371

# jwt
jwt.algorithm = rs256

# 是否桥接
dgiot_api.isbridge = false
# 是否桥接
dgiot_api.bridge_url = https://prod.dgiotcloud.cn

# onenet
onenet.server = https://prod.dgiotcloud.cn
onenet.appid = <redacted>
onenet.secret = <redacted>
