// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dlink.proto

package io.grpc.examples.dlink;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dgiot.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dgiot.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.dgiot.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The status.
   */
  io.grpc.examples.dlink.HealthCheckResponse.ServingStatus getStatus();
}
