// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dlink.proto

package io.grpc.examples.dlink;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dgiot.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
