= Gun

Gun is an Erlang HTTP client with support for HTTP/1.1, HTTP/2 and Websocket.

== Goals

Gun aims to provide an *easy to use* client compatible with
HTTP/1.1, HTTP/2 and Websocket.

Gun is *always connected*. It will maintain a permanent
connection to the server, reopening it as soon as the server
closes it, saving time for the requests that come in.

All connections are *supervised* automatically, allowing
developers to focus on writing their code without worrying.

== Sponsors

The project is currently sponsored by
https://kato.im[Kato.im] and https://sameroom.io[Sameroom].

The now removed SPDY implementation was sponsored by
http://www.leofs.org[LeoFS Cloud Storage].

== Online documentation

* https://ninenines.eu/docs/en/gun/1.3/guide[User guide]
* https://ninenines.eu/docs/en/gun/1.3/manual[Function reference]

== Offline documentation

* While still online, run `make docs`
* User guide available in `doc/` in PDF and HTML formats
* Function reference man pages available in `doc/man3/` and `doc/man7/`
* Run `make install-docs` to install man pages on your system
* Full documentation in Asciidoc available in `doc/src/`

== Getting help

* Official IRC Channel: #ninenines on irc.freenode.net
* https://github.com/ninenines/gun/issues[Issues tracker]
* https://ninenines.eu/services/[Commercial Support]
